### ISSUE TITLE
Creation of an Animal Observation record (Web) - Part 1

### ISSUE THREAD

**Issue by mikeshasko** [bcgov/lucy-web#293]
As a Invasive Animal Specialist, I want to create a basic animal observation record to identify an observed occurrence of an invasive animal within the WEB interface

**Additional Context**

**Part 1 consists on the database constructions of:**

a) animal observation database table (see attached image for the basic variables) (exclude the region and affiliation  variable). Adopt the same geom structure from plants to accommodate location and geometry
b) invasive animals species table  (the dropdown of 125 invasive animals is required - see attached txt file)
c) creation of the "Life Stage" lookup table (see below for the 5 elements)
d) creation of the "Behaviour" lookup table (see below for the 4 elements)
e) re-use the same plant agency table
 

**Acceptance Criteria**
- [x] creation of the main invasive animal observation database table
- [x] creation of the invasive animals species table
- [x] creation of the life stage table
- [x] creation of the behaviour table
- [x] link to the plant agency table

**Comment by mikeshasko** [comment]
[https://app.zenhub.com/files/181950649/cf5ac929-32e9-4dce-90ae-db1bfee02ac9/download](https://app.zenhub.com/files/181950649/cf5ac929-32e9-4dce-90ae-db1bfee02ac9/download)

Create a table to house all the variables.
The dropdown list is to only include the "Common name"

**Comment by mikeshasko** [comment]
![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/d7d94cf6-74d2-4449-bb24-3cd53b6854a6)

**Comment by rajfreshworks** [comment]
The backend routes for the animal observation and a test case for each of them is also added as a part of this ticket
